DROP SEQUENCE PERSON_SQ
/
DROP TABLE PERSON
/

CREATE TABLE PERSON(
PERSON_ID    NUMBER(10)     NOT NULL,
FIRSTNAME    VARCHAR2(200)  NOT NULL,
LASTNAME     VARCHAR2(200)  NOT NULL,
SEX          VARCHAR2(1)    NOT NULL,
BIRTHDATE    DATE           NULL,
CREATE_DATE  DATE           SYSDATE,
CONSTRAINT PK_PERSON PRIMARY KEY(PERSON_ID)
)
/

CREATE SEQUENCE PERSON_SQ START WITH 1 CACHE 20 NOCYCLE
/

--
SELECT * FROM PERSON ORDER BY 1
/

/*
DELETE FROM PERSON WHERE person_id IN (13,14);
COMMIT;
*/
