INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'LUCIANO', 'CARMO', 'M', TO_DATE('1982-01-27','YYYY-MM-DD'), SYSDATE);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'PRISCILA', 'CARMO', 'F', TO_DATE('1978-01-28','YYYY-MM-DD'), SYSDATE);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'EDUARDO', 'LEITE', 'M', TO_DATE('1978-09-09','YYYY-MM-DD'), SYSDATE);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'ROGERIO', 'SILVA', 'M', TO_DATE('1979-11-09','YYYY-MM-DD'), SYSDATE);
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'ROGERIO', 'FERNANDES', 'M', TO_DATE('1970-02-03','YYYY-MM-DD'), SYSDATE);
COMMIT
/