INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'LUCIANO', 'SILVA', 'M', TO_DATE('1982-01-27','YYYY-MM-DD'), SYSDATE)
INSERT INTO PERSON VALUES (PERSON_SQ.NEXTVAL, 'EDUARDO', 'LEITE', 'M', TO_DATE('1978-09-09','YYYY-MM-DD'), SYSDATE)
/
COMMIT
/